In [1]:
import numpy as np

In [2]:
a =np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
b =np.array([(1.5,2,3),(4,5,6)], dtype =float)
print(b)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [4]:
a.sum()

6

In [6]:
b.sum()

21.5

In [7]:
a.min()

1

In [8]:
b.min()

1.5

In [9]:
b.max(axis=0)

array([4., 5., 6.])

In [10]:
b.max(axis=1)

array([3., 6.])

In [11]:
b.cumsum(axis=1)

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [12]:
a.mean()

2.0

In [13]:
b.mean()

3.5833333333333335

In [14]:
np.median(a)

2.0

In [15]:
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [16]:
np.median(b)

3.5

In [17]:
np.std(b)

1.5920810978785667

In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [21]:
df = pd.DataFrame({'New York': [25]})
df

New York
0        25

In [22]:
 df.melt()

variable  value
0  New York     25

In [23]:
df = pd.DataFrame({'New york': [25], 'Paris': [27], 'London': [30]})
df

New york  Paris  London
0        25     27      30

In [24]:
df.melt()

variable  value
0  New york     25
1     Paris     27
2    London     30

In [26]:
df_larger = pd.DataFrame({
    'New york': [25, 27, 23, 25, 29],
    'Paris': [27, 22, 24, 26, 28],
    'London': [30, 31, 33, 29, 25]
})
df_larger

New york  Paris  London
0        25     27      30
1        27     22      31
2        23     24      33
3        25     26      29
4        29     28      25

In [27]:
df_larger.melt()

variable  value
0   New york     25
1   New york     27
2   New york     23
3   New york     25
4   New york     29
5      Paris     27
6      Paris     22
7      Paris     24
8      Paris     26
9      Paris     28
10    London     30
11    London     31
12    London     33
13    London     29
14    London     25

In [28]:
df.melt(var_name='city', value_name='temperature')

city  temperature
0  New york           25
1     Paris           27
2    London           30

In [29]:
temperatures = pd.DataFrame({
    'city': ['New York', 'London', 'Paris', 'Berlin', 'Amsterdam'],
    'day1': [23, 25, 27, 26, 24],
    'day2': [22, 21, 25, 26, 23],
    'day3': [26, 25, 24, 27, 23],
    'day4': [23, 21, 22, 26, 27],
    'day5': [27, 26, 27, 24, 28]
})
temperatures

city  day1  day2  day3  day4  day5
0   New York    23    22    26    23    27
1     London    25    21    25    21    26
2      Paris    27    25    24    22    27
3     Berlin    26    26    27    26    24
4  Amsterdam    24    23    23    27    28

In [30]:
 temperatures.melt()

variable      value
0      city   New York
1      city     London
2      city      Paris
3      city     Berlin
4      city  Amsterdam
5      day1         23
6      day1         25
7      day1         27
8      day1         26
9      day1         24
10     day2         22
11     day2         21
12     day2         25
13     day2         26
14     day2         23
15     day3         26
16     day3         25
17     day3         24
18     day3         27
19     day3         23
20     day4         23
21     day4         21
22     day4         22
23     day4         26
24     day4         27
25     day5         27
26     day5         26
27     day5         27
28     day5         24
29     day5         28

In [31]:
temperatures.melt(id_vars=['city'])

city variable  value
0    New York     day1     23
1      London     day1     25
2       Paris     day1     27
3      Berlin     day1     26
4   Amsterdam     day1     24
5    New York     day2     22
6      London     day2     21
7       Paris     day2     25
8      Berlin     day2     26
9   Amsterdam     day2     23
10   New York     day3     26
11     London     day3     25
12      Paris     day3     24
13     Berlin     day3     27
14  Amsterdam     day3     23
15   New York     day4     23
16     London     day4     21
17      Paris     day4     22
18     Berlin     day4     26
19  Amsterdam     day4     27
20   New York     day5     27
21     London     day5     26
22      Paris     day5     27
23     Berlin     day5     24
24  Amsterdam     day5     28

In [32]:
temperatures.melt(id_vars=['city'],
                  var_name='date',
                  value_name='temperature').sample(5)

city  date  temperature
3      Berlin  day1           26
4   Amsterdam  day1           24
18     Berlin  day4           26
24  Amsterdam  day5           28
2       Paris  day1           27

In [ ]:
stocks = pd.read_csv('data/prices-split-adjusted.csv',
                     usecols=['date', 'symbol', 'open', 'close'],
                     parse_dates=['date'],
                     index_col='date')
stocks.head()